// SEO report types (exported from jobs.ts for convenience)
export type {
  AssetBreakdown,
  AssetCategoryBreakdown,
  AssetSample,
  AuditPriority,
  AuditSeverity,
  SEOReport,
  SEOCategory,
  SEOCategoryScore,
  SEORecommendation,
  SEOFinding,
  SEOAuditSummary,
  WhoisData,
  DNSRecords,
  SSLCertificate,
  HTTPHeaders,
  MetaTags,
  HeadingCounts,
  PageImageSummary,
  PageLinkSummary,
  PageAssetType,
  PageAsset,
  TechDetection,
  RobotsData,
  SitemapData,
  PerformanceScore,
  RenderingRisk,
  SERPPreview,
  SocialPresence,
} from './jobs';
